Add deploy script for yggdrasil

diff --git a/deploy/yggdrasil b/deploy/yggdrasil
--- a/deploy/yggdrasil
+++ b/deploy/yggdrasil
@@ -1,19 +1,10 @@
 #!/bin/bash
 
-install_destination=/opt/epicyon-i2p
-username='epicyon-i2p'
+install_destination=/opt/epicyon-yggdrasil
+username='epicyon-yggdrasil'
 
 if [[ "$1" == 'remove' ]]; then
-    echo 'Removing Epicyon i2p instance'
-    systemctl stop i2pd
-    if [ -f /var/lib/i2pd/tunnels.d/epicyon ]; then
-        rm /var/lib/i2pd/tunnels.d/epicyon
-    fi
-    if [ -f /etc/i2pd/tunnels.conf.d/epicyon ]; then
-        rm /etc/i2pd/tunnels.conf.d/epicyon
-    fi
-    rm /var/lib/i2pd/epicyon.dat
-    systemctl restart i2pd
+    echo 'Removing Epicyon yggdrasil instance'
 
     systemctl stop "${username}.service"
     systemctl disable "${username}.service"
@@ -21,35 +12,24 @@ if [[ "$1" == 'remove' ]]; then
     rm "/etc/nginx/sites-availale/${username}"
     rm -rf ${install_destination}
     userdel -r ${username}
-    echo 'Epicyon i2p instance removed'
+    echo 'Epicyon yggdrasil instance removed'
     exit 0
 fi
 
-if [[ "$1" == 'removei2p' ]]; then
+if [[ "$1" == 'removeyggdrasil' ]]; then
     if [ -f /usr/bin/pacman ]; then
-        pacman -R --noconfirm i2pd
+        pacman -R --noconfirm yggdrasil
     else
-        apt-get -y remove --purge i2pd
+        apt-get -y remove --purge yggdrasil
     fi
-    rm -rf /etc/i2pd
-    rm -rf /var/lib/i2pd
-    if [ -f /var/log/i2pd/i2pd.log ]; then
-        rm /var/log/i2pd/i2pd.log
-    fi
+    rm -rf /etc/yggdrasil
 fi
 
 clear
-echo 'Installing Epicyon on an i2p domain'
+echo 'Installing Epicyon on a yggdrasil address'
 
-NGINX_PORT=9554
-EPICYON_PORT=7158
-tunnels_dir=/var/lib/i2pd/tunnels.d
-
-# if proxychains already exists then make a copy of the
-# older config
-if [ -f /etc/proxychains.conf ]; then
-    mv /etc/proxychains.conf /etc/proxychains.conf.old
-fi
+NGINX_PORT=9555
+EPICYON_PORT=7159
 
 echo 'Adding Epicyon dependencies'
 if [ -f /usr/bin/pacman ]; then
@@ -57,8 +37,8 @@ if [ -f /usr/bin/pacman ]; then
     pacman -S --noconfirm python-pip python-pysocks python-cryptography \
            imagemagick python-pillow python-requests \
            perl-image-exiftool python-numpy python-dateutil \
-           certbot flake8 git i2pd wget qrencode \
-           proxychains midori bandit
+           certbot flake8 git wget qrencode \
+           proxychains midori bandit yggdrasil
     pip3 install pyqrcode pypng
 else
     apt-get update
@@ -67,13 +47,13 @@ else
             python3-numpy python3-pil.imagetk python3-pip \
             python3-setuptools python3-socks python3-idna \
             libimage-exiftool-perl python3-flake8 \
-            python3-django-timezone-field nginx git i2pd wget \
+            python3-django-timezone-field nginx git wget \
             python3-pyqrcode qrencode python3-png \
-            proxychains midori python3-bandit
+            proxychains midori python3-bandit yggdrasil
 fi
 
-if [ ! -d /etc/i2pd ]; then
-    echo 'i2pd was not installed'
+if [ ! -d /etc/yggdrasil ]; then
+    echo 'yggdrasil was not installed'
     exit 5
 fi
 
@@ -99,46 +79,6 @@ fi
 
 chown -R ${username}:${username} ${install_destination}
 
-echo 'Creating a command script to obtain i2p domain names from dat files'
-{ echo '#!/bin/bash';
-  echo "tunnelname=\"\$1\"";
-  echo 'domainfile=/tmp/i2pdomain.txt';
-  echo "if [ -f \${domainfile} ]; then";
-  echo "    rm \${domainfile}";
-  echo 'fi';
-  echo "wget http://127.0.0.1:7070/?page=i2p_tunnels -O \${domainfile} 2> /dev/null";
-  echo "if [ ! -f \${domainfile} ]; then";
-  echo '    exit 9';
-  echo 'fi';
-  echo "awk -F \">\${tunnelname}<\" '{print \$2}' < \${domainfile} | awk -F ';' '{print \$2}' | awk -F ':' '{print \$1}' | tr -d '[:space:]'";
-  echo "rm \${domainfile}"; } > /usr/bin/i2pdomain
-chmod +x /usr/bin/i2pdomain
-
-echo 'Creating Epicyon i2p tunnel file'
-if [ ! -d "$tunnels_dir" ]; then
-    ln -s /etc/i2pd/tunnels.conf.d /var/lib/i2pd/tunnels.d
-fi
-
-if ! grep -q 'epicyon.dat' /var/lib/i2pd/tunnels.conf; then
-    { echo '';
-      echo '[epicyon]';
-      echo 'type = http';
-      echo 'host = 127.0.0.1';
-      echo 'inport = 80';
-      echo "port = ${NGINX_PORT}";
-      echo 'inbound.length = 1';
-      echo 'inbound.quantity = 5';
-      echo 'outbound.length = 1';
-      echo 'outbound.quantity = 5';
-      echo "keys = epicyon.dat"; } >> /var/lib/i2pd/tunnels.conf
-fi
-rm "$tunnels_dir"/*~
-
-echo 'Setting i2p tunnels directory'
-sed -i 's|#tunnelsdir =|tunnelsdir =|g' /etc/i2pd/i2pd.conf
-sed -i 's|# tunnelsdir =|tunnelsdir =|g' /etc/i2pd/i2pd.conf
-sed -i "s|tunnelsdir =.*|tunnelsdir = $tunnels_dir|g" /etc/i2pd/i2pd.conf
-
 echo 'Enabling ipv6'
 if [ -f /etc/sysctl.conf ]; then
     if grep -q 'net.ipv6.conf.all.disable_ipv6' /etc/sysctl.conf; then
@@ -146,61 +86,26 @@ if [ -f /etc/sysctl.conf ]; then
         /sbin/sysctl -p -q
     fi
 fi
-sed -i 's|#ipv6 =|ipv6 =|g' /etc/i2pd/i2pd.conf
-sed -i 's|# ipv6 =|ipv6 =|g' /etc/i2pd/i2pd.conf
-sed -i 's|ipv6 =.*|ipv6 = true|g' /etc/i2pd/i2pd.conf
 
-echo 'Disabling i2p logging'
-sed -i 's|#logfile =|logfile =|g' /etc/i2pd/i2pd.conf
-sed -i 's|# logfile =|logfile =|g' /etc/i2pd/i2pd.conf
-sed -i 's|logfile =.*|logfile = /dev/null|g' /etc/i2pd/i2pd.conf
+echo 'Creating a command script to obtain yggdrasil address'
+{ echo '#!/bin/bash';
+  echo "sudo yggdrasilctl getself | grep \"IPv6 address\" | awk -F ' ' '{print $3}'"; } > /usr/bin/yggdrasil-address
+chmod +x /usr/bin/yggdrasil-address
 
-echo 'Enabling i2p NAT traversal'
-sed -i 's|#nat =|nat =|g' /etc/i2pd/i2pd.conf
-sed -i 's|# nat =|nat =|g' /etc/i2pd/i2pd.conf
-sed -i 's|nat =.*|nat = true|g' /etc/i2pd/i2pd.conf
+echo 'Creating yggdrasil configuration'
+sudo yggdrasil -genconf | sudo tee /etc/yggdrasil/yggdrasil.conf
+sudo systemctl enable yggdrasil
+sudo systemctl restart yggdrasil
 
-if [ ! -d /run/i2pd ]; then
-    mkdir /run/i2pd
-fi
-chown -R i2pd:i2pd /run/i2pd
-
-#if [ -f /usr/bin/pacman ]; then
-#    sed -i 's|ExecStart=.*|ExecStart=/usr/sbin/i2pd --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.conf --tunnelsdir=/etc/i2pd/tunnels.conf.d --service|g' /lib/systemd/system/i2pd.service
-#    sed -i 's|Type=.*|Type=simple|g' /lib/systemd/system/i2pd.service
-#fi
-
-echo 'Setting file permissions'
-chown -R i2pd:i2pd "$tunnels_dir"
-chmod 644 "$tunnels_dir"/*
-chmod 755 "$tunnels_dir"
-# chown -R i2pd:i2pd /etc/i2pd
-systemctl daemon-reload
-systemctl enable i2pd
-systemctl restart i2pd
-
-echo 'Waiting for i2p daemon restart'
 sleep 5
-if [ ! -f /var/lib/i2pd/epicyon.dat ]; then
-    echo 'Waiting for i2p daemon restart...'
-    sleep 5
+
+YGGDRASIL_ADDRESS=$(/usr/bin/yggdrasil-address)
+if [ ! "${YGGDRASIL_ADDRESS}" ]; then
+	echo 'yggdrassil could not be started'
+	exit 73
 fi
 
-if [ ! -f /var/lib/i2pd/epicyon.dat ]; then
-    echo '/var/lib/i2pd/epicyon.dat not created'
-    exit 6
-fi
-
-echo '/var/lib/i2pd/epicyon.dat file was created'
-
-I2P_DOMAIN=$(i2pdomain epicyon)
-if [[ "$I2P_DOMAIN" != *'.i2p' ]]; then
-    echo 'Epicyon i2p domain not created'
-    echo "$I2P_DOMAIN"
-    exit 1
-fi
-
-echo "i2p domain: http://${I2P_DOMAIN}"
+echo "Your yggdrassil address is: http://[${YGGDRASIL_ADDRESS}]"
 
 echo 'Creating Epicyon daemon'
 { echo '[Unit]';
@@ -213,7 +118,7 @@ echo 'Creating Epicyon daemon'
   echo "User=$username";
   echo "Group=$username";
   echo "WorkingDirectory=${install_destination}";
-  echo "ExecStart=/usr/bin/python3 ${install_destination}/epicyon.py --http --i2p --bind 0.0.0.0 --port 80 --proxy ${EPICYON_PORT} --domain ${I2P_DOMAIN} --registration open";
+  echo "ExecStart=/usr/bin/python3 ${install_destination}/epicyon.py --http --yggdrasil --bind 0.0.0.0 --port 80 --proxy ${EPICYON_PORT} --domain ${YGGDRASIL_ADDRESS} --registration open";
   echo "Environment=USER=$username";
   echo 'Environment=PYTHONUNBUFFERED=true';
   echo 'Environment=PYTHONIOENCODING=utf-8';
@@ -343,14 +248,15 @@ if [ -f /usr/bin/pacman ]; then
     web_dir=/srv/http
 fi
 
-if [ ! -d /var/www/${I2P_DOMAIN}/htdocs ]; then
-	mkdir -p /var/www/${I2P_DOMAIN}/htdocs
+if [ ! -d /var/www/${YGGDRASIL_ADDRESS}/htdocs ]; then
+	mkdir -p /var/www/${YGGDRASIL_ADDRESS}/htdocs
 fi
 
-echo "Creating nginx virtual host for http://${I2P_DOMAIN}"
+echo "Creating nginx virtual host for http://[${YGGDRASIL_ADDRESS}]"
 { echo 'server {';
-  echo "    listen 127.0.0.1:${NGINX_PORT} default_server;";
-  echo "    server_name ${I2P_DOMAIN};"
+  echo '    listen 80;';
+  echo '    listen [::]:80;';
+  echo "    server_name ${YGGDRASIL_ADDRESS};"
   echo '';
   echo '    gzip            on;';
   echo '    gzip_min_length 1000;';
@@ -369,7 +275,7 @@ echo "Creating nginx virtual host for http://${I2P_DOMAIN}"
   echo '    index index.html;';
   echo '';
   echo '    location /newsmirror {';
-  echo "      root /var/www/${I2P_DOMAIN}/htdocs;";
+  echo "      root /var/www/${YGGDRASIL_ADDRESS}/htdocs;";
   echo '      try_files $uri =404;';
   echo '    }';
   echo '';
@@ -399,51 +305,34 @@ echo "Creating nginx virtual host for http://${I2P_DOMAIN}"
 ln -s /etc/nginx/sites-available/${username} /etc/nginx/sites-enabled/
 systemctl restart nginx
 
-# set up socks5 proxy for browser
-{ echo 'dynamic_chain';
-  echo 'proxy_dns';
-  echo 'remote_dns_subnet 224';
-  echo 'tcp_read_time_out 15000';
-  echo 'tcp_connect_time_out 8000';
-  echo 'localnet 127.0.0.0/255.0.0.0';
-  echo '[ProxyList]';
-  echo 'http    127.0.0.1 4444';
-  echo 'socks5  127.0.0.1 4447'; } > /etc/proxychains.conf
-
 # set up a desktop icon
 for d in /home/*/ ; do
     CURRUSER=$(echo "$d" | awk -F '/' '{print $3}')
     if [ -d "/home/${CURRUSER}/Desktop" ]; then
         { echo '#!/usr/bin/env xdg-open';
           echo '[Desktop Entry]';
-          echo 'Name=Epicyon I2P';
+          echo 'Name=Epicyon yggdrasil';
           echo 'GenericName=P2P Social Network';
           echo 'Comment=P2P Social Network';
-          echo "Exec=proxychains midori http://${I2P_DOMAIN}";
+          echo "Exec=midori http://[${YGGDRASIL_ADDRESS}]";
           echo 'Icon=org.midori_browser.Midori';
           echo 'Type=Application';
           echo 'Terminal=false';
           echo 'Categories=Internet;SocialNetwork;';
           echo 'StartupWMClass=Epicyon';
-          echo 'Keywords=Epicyon;P2P;I2P;'; } > "/home/${CURRUSER}/Desktop/${username}.desktop"
+          echo 'Keywords=Epicyon;P2P;yggdrasil;'; } > "/home/${CURRUSER}/Desktop/${username}.desktop"
         chown "$CURRUSER":"$CURRUSER" "/home/${CURRUSER}/Desktop/${username}.desktop"
     fi
 done
 
 clear
-echo -n "$I2P_DOMAIN" | qrencode -t ANSI
-echo 'Your Epicyon i2p instance is now installed.'
+echo -n "${YGGDRASIL_ADDRESS}" | qrencode -t ANSI
+echo 'Your Epicyon yggdrasil instance is now installed.'
 echo ''
-echo 'You can view it from the terminal with the command:'
+echo 'You can view it in your preferred browser by navigating to:'
 echo ''
-echo '    proxychains midori'
+echo "http://[${YGGDRASIL_ADDRESS}]"
 echo ''
-echo 'If you prefer Firefox then see preferences/network settings, '
-echo 'manual proxy and uncheck DNS over HTTPS. In about:config and '
-echo 'find the property media.peerConnection.ice.proxy_only and set '
-echo 'it to true. http should be proxied through 127.0.0.1 port 4444 '
-echo 'and socks5 proxied through 127.0.0.1 port 4447.'
-echo ''
-echo "Navigate to http://${I2P_DOMAIN} and register an account."
+echo 'Then register an account.'
 
 exit 0
